# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('errands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='errand',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='errand',
            name='category',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('HOMEWORK', 'Homework'), ('ETC', 'Etc')], default='DELIVERY', max_length=10),
        ),
        migrations.AlterField(
            model_name='errand',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='errand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errands.Errand'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
