# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.AddField(
            model_name='user',
            name='review_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
